services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_image:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=dbname
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
    depends_on:
      - database
    command: python ./script/main.py

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: